openapi: 3.1.0
info:
  title: Prova API
  description: Universal ZK proof verification layer
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://api.prova.io
    description: Production
  - url: http://localhost:3000
    description: Local development

security:
  - ApiKeyAuth: []

paths:
  /health:
    get:
      summary: Health check
      operationId: health
      security: []
      tags:
        - System
      responses:
        "200":
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"

  /v1/verify:
    post:
      summary: Verify a proof
      operationId: verify
      tags:
        - Verification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VerifyRequest"
      responses:
        "200":
          description: Verification result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VerifyResponse"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "422":
          description: Unsupported prover
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /v1/proof/{proofId}:
    get:
      summary: Get proof by ID
      operationId: getProof
      tags:
        - Proofs
      parameters:
        - name: proofId
          in: path
          required: true
          schema:
            type: string
          description: Canonical proof ID
      responses:
        "200":
          description: Proof details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProofResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Proof not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /v1/provers:
    get:
      summary: List supported provers
      operationId: listProvers
      security: []
      tags:
        - Provers
      responses:
        "200":
          description: List of provers
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListProversResponse"

  /v1/provers/{prover}/versions:
    get:
      summary: List prover versions
      operationId: listVersions
      security: []
      tags:
        - Provers
      parameters:
        - name: prover
          in: path
          required: true
          schema:
            type: string
          description: Prover name (e.g., snarkjs, zisk)
      responses:
        "200":
          description: List of versions
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListVersionsResponse"

  /v1/provers/{prover}/{version}:
    get:
      summary: Get version details
      operationId: getVersionDetail
      security: []
      tags:
        - Provers
      parameters:
        - name: prover
          in: path
          required: true
          schema:
            type: string
        - name: version
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Version details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VersionDetailResponse"

  /internal/api-keys/provision:
    post:
      summary: Provision API key for user
      description: |
        Internal endpoint for frontend to provision API keys after OAuth login.
        Protected by X-Internal-Secret header.
      operationId: provisionApiKey
      security:
        - InternalAuth: []
      tags:
        - Internal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProvisionApiKeyRequest"
      responses:
        "200":
          description: API key provisioned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProvisionApiKeyResponse"
        "401":
          description: Invalid internal secret
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: API key for authentication
    InternalAuth:
      type: apiKey
      in: header
      name: X-Internal-Secret
      description: Shared secret for internal frontend-gateway communication

  schemas:
    HealthResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          example: ok

    VerifyRequest:
      type: object
      required:
        - proof
      properties:
        proof:
          type: object
          description: Proof data (format depends on prover)
        public_inputs:
          type: array
          items:
            type: string
          description: Public inputs for verification
        prover:
          type: string
          enum: [zisk]
          description: Prover to use (defaults to zisk)
        proof_system:
          type: string
          enum: [zisk]
          description: Proof system (defaults to zisk)

    VerifyResponse:
      type: object
      required:
        - valid
        - proof_system
        - prover
        - prover_version
        - verified_at
      properties:
        valid:
          type: boolean
          description: Whether the proof is valid
        proof_id:
          type: string
          description: Canonical proof ID (only if valid)
        proof_system:
          type: string
        prover:
          type: string
        prover_version:
          type: string
        public_inputs_hash:
          type: string
        verified_at:
          type: string
          format: date-time
        error:
          type: string
          description: Error message if verification failed

    ProofResponse:
      type: object
      required:
        - proof_id
        - proof_system
        - prover
        - prover_version
        - valid
        - verified_at
      properties:
        proof_id:
          type: string
        proof_system:
          type: string
        prover:
          type: string
        prover_version:
          type: string
        public_inputs_hash:
          type: string
        valid:
          type: boolean
        verified_at:
          type: string
          format: date-time

    ListProversResponse:
      type: object
      required:
        - provers
      properties:
        provers:
          type: array
          items:
            $ref: "#/components/schemas/ProverInfo"

    ProverInfo:
      type: object
      required:
        - name
        - proof_systems
      properties:
        name:
          type: string
        proof_systems:
          type: array
          items:
            type: string

    ListVersionsResponse:
      type: object
      required:
        - prover
        - versions
      properties:
        prover:
          type: string
        versions:
          type: array
          items:
            $ref: "#/components/schemas/VersionInfo"

    VersionInfo:
      type: object
      required:
        - version
        - active
        - proof_systems
      properties:
        version:
          type: string
        active:
          type: boolean
        proof_systems:
          type: array
          items:
            type: string

    VersionDetailResponse:
      type: object
      required:
        - prover
        - version
        - proof_systems
        - registered_at
      properties:
        prover:
          type: string
        version:
          type: string
        proof_systems:
          type: array
          items:
            $ref: "#/components/schemas/ProofSystemInfo"
        registered_at:
          type: string
          format: date-time

    ProofSystemInfo:
      type: object
      required:
        - name
        - vk_hash
        - active
      properties:
        name:
          type: string
        vk_hash:
          type: string
        active:
          type: boolean

    ProvisionApiKeyRequest:
      type: object
      required:
        - user_id
        - email
      properties:
        user_id:
          type: string
          description: User ID from OAuth provider
        email:
          type: string
          format: email
          description: User email

    ProvisionApiKeyResponse:
      type: object
      required:
        - api_key
        - created
      properties:
        api_key:
          type: string
          description: API key (only shown once on creation)
        created:
          type: boolean
          description: True if newly created, false if existing key returned

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message
